# QCM Generator Pro - Docker Compose Configuration

# Load environment variables from .env.docker file
# Copy .env.docker.example to .env.docker and set your API keys
services:
  # Ollama Service (Local LLM Server)
  ollama:
    image: ollama/ollama:latest
    container_name: qcm_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - qcm_network
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Main QCM Application (FastAPI + Streamlit)
  qcm_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: qcm_generator_pro
    env_file:
      - .env.docker
    ports:
      - "8001:8001"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - qcm_uploads:/app/uploads
    environment:
      # Docker Environment
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      
      # Database
      - DATABASE_URL=sqlite:///./data/database/qcm_generator.db
      
      # LLM Configuration
      - LLM_DEFAULT_MODEL=gpt-4o-mini
      - LLM_MODEL_TYPE=openai
      - LLM_OLLAMA_BASE_URL=http://ollama:11434
      - LLM_OLLAMA_TIMEOUT=120
      - OLLAMA_AUTO_DOWNLOAD_MODELS=false
      - LLM_OPENAI_API_KEY=${LLM_OPENAI_API_KEY:-}
      - LLM_OPENAI_MODEL=${LLM_OPENAI_MODEL:-}
      - LLM_OPENAI_TIMEOUT=${LLM_OPENAI_TIMEOUT:-}
      - LLM_ANTHROPIC_API_KEY=${LLM_ANTHROPIC_API_KEY:-}
      - LLM_ANTHROPIC_MODEL=${LLM_ANTHROPIC_MODEL:-}
      - LLM_ANTHROPIC_TIMEOUT=${LLM_ANTHROPIC_TIMEOUT:-}
      - LLM_DEFAULT_TEMPERATURE=0.7
      - LLM_DEFAULT_MAX_TOKENS=512
      - LLM_DEFAULT_TOP_P=0.9
      
      # Processing Configuration
      - PROCESSING_CHUNK_SIZE=2000
      - PROCESSING_CHUNK_OVERLAP=200
      - PROCESSING_MAX_PDF_SIZE_MB=50
      
      # Server Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - UI_HOST=0.0.0.0
      - UI_PORT=8501
      
      # Application Configuration
      - APP_NAME=QCM Generator Pro
      - DEBUG=false
      - ENVIRONMENT=production
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - qcm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis Cache (Optional - for future scaling)
  redis:
    image: redis:7-alpine
    container_name: qcm_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - qcm_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
    driver: local
  redis_data:
    driver: local
  qcm_uploads:
    driver: local

networks:
  qcm_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16