# QCM Generator Pro - Docker Compose Configuration (CPU Only)
services:
  # Ollama Service (Local LLM Server - CPU Only)
  ollama:
    image: ollama/ollama:latest
    container_name: qcm_ollama_cpu
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
    restart: unless-stopped
    networks:
      - qcm_network
    healthcheck:
      test: ["CMD", "/bin/ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Main QCM Application (FastAPI + Streamlit)
  qcm_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: qcm_generator_pro
    env_file:
      - .env.docker
    ports:
      - "8001:8001"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - qcm_uploads:/app/uploads
    environment:
      # Docker Environment
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      
      # Database
      - DATABASE_URL=sqlite:///./data/database/qcm_generator.db
      
      # LLM Configuration (CPU optimized)
      - LLM_DEFAULT_MODEL=ollama
      - LLM_MODEL_TYPE=ollama
      - LLM_OLLAMA_BASE_URL=http://ollama:11434
      - LLM_OLLAMA_TIMEOUT=300
      - OLLAMA_AUTO_DOWNLOAD_MODELS=false
      - LLM_DEFAULT_TEMPERATURE=0.7
      - LLM_DEFAULT_MAX_TOKENS=512
      - LLM_DEFAULT_TOP_P=0.9
      
      # Processing Configuration
      - PROCESSING_CHUNK_SIZE=1000
      - PROCESSING_CHUNK_OVERLAP=100
      - PROCESSING_MAX_PDF_SIZE_MB=25
      
      # Server Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8001
      - UI_HOST=0.0.0.0
      - UI_PORT=8501
      
      # Application Configuration
      - APP_NAME=QCM Generator Pro
      - DEBUG=false
      - ENVIRONMENT=production
    depends_on:
      ollama:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - qcm_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  ollama_data:
    driver: local
  qcm_uploads:
    driver: local

networks:
  qcm_network:
    driver: bridge