# QCM Generator Pro - Simple CI
# Lightweight workflow for getting started

name: Simple CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: "3.11"
  
jobs:
  # Basic checks and tests
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        
    - name: Run linting
      run: ruff check src tests --output-format=github
      continue-on-error: true
      
    - name: Run basic tests
      run: |
        pytest tests/ -v --tb=short
      continue-on-error: true